### ISSUE TITLE
Anwendung braucht manchmal lange zum starten

### ISSUE THREAD

**Issue by FlorianJa** [FlorianJa/ExtendedPrinter-Unity#4]
Unter bestimmten Umständen braucht die Anwendung sehr lange zum Starten. Damit ist die Zeit zwischen dem Unity Logo und dem Erscheinen des Cursors gemeint. Dieses Phänomen tritt vor allem dann auf, wenn sich viele Personen um den Drucker herum befinden. Vermutlich hat das was mit der WLan Verbindung zu tun. Die Abfrage der Dateien auf dem OctoPrint laufen eigentlich async und sollten somit kein Problem darstellen. Das müsste eventuell noch mal im Detail überprüft werden.

**Comment by FlorianJa** [comment]
Ich glaube das Problem liegt an Vuforia. Ich hatte ähnliches Problem bei einer anderen Anwendung, in der kein Ntzwerkkram drin ist.

**Comment by Grosskopf** [comment]
Bei vuforia findet wohl das Nachladen von Configs nach dem ersten deploy statt, dies kann man wohl künstlich unterbinden
